<?php

return [
    [
        'type'       => 'item',
        'label'      => 'Tableau de bord',
        'icon'       => 'home',
        'route'      => 'dashboard',
        'permission' => null,
    ],
    ['type' => 'separator', 'label' => 'COMMERCE'],
    [
        'type'       => 'group',
        'label'      => 'Articles',
        'icon'       => 'cube',
        'permission' => 'manage products',
        'items'      => [
            ['label' => 'Lister les articles', 'route' => 'products.index'],
            ['label' => 'Ajouter un article',  'route' => 'products.create'],
            ['label' => 'Unités',              'route' => 'units.index'],
            ['label' => 'Catégories',          'route' => 'categories.index'],
        ],
    ],
    [
        'type'       => 'group',
        'label'      => 'Achats',
        'icon'       => 'shopping-cart',
        'permission' => 'manage purchases',
        'items'      => [
            ['label' => 'Lister les achats',  'route' => 'purchases.index'],
            ['label' => 'Ajouter un achat',   'route' => 'purchases.create'],
            ['label' => 'Retours d\'achat',   'route' => 'purchase-returns.index'],
        ],
    ],
    [
        'type'       => 'group',
        'label'      => 'Point de vente (POS)',
        'icon'       => 'currency-dollar',
        'permission' => 'manage pos',
        'items'      => [
            ['label' => 'Caisse (POS)',       'route' => 'pos.index'],
            ['label' => 'Historique POS',     'route' => 'pos.list'],
            ['label' => 'Retours de vente',   'route' => 'pos.returns.index'],
            ['label' => 'Sessions de caisse', 'route' => 'pos.sessions.index'],
            ['label' => 'Liste des caisses',  'route' => 'pos.caisses.index'],
        ],
    ],
    ['type' => 'separator', 'label' => 'STOCK'],
    [
        'type'       => 'item',
        'label'      => 'État de stock',
        'route'      => 'stock-status.index',
        'icon'       => 'chart-bar',
        'permission' => 'manage stock',
    ],
    [
        'type'       => 'group',
        'label'      => 'Transferts de stock',
        'icon'       => 'arrows-right-left',
        'permission' => 'manage stock',
        'items'      => [
            ['label' => 'Liste des transferts', 'route' => 'stock-transfers.index'],
            ['label' => 'Ajouter un transfert', 'route' => 'stock-transfers.create'],
        ],
    ],
    [
        'type'       => 'group',
        'label'      => 'Ajustement de stock',
        'icon'       => 'adjustments-horizontal',
        'permission' => 'manage stock',
        'items'      => [
            ['label' => 'Liste des ajustements', 'route' => 'stock-adjustments.index'],
            ['label' => 'Ajouter un ajustement', 'route' => 'stock-adjustments.create'],
        ],
    ],
    ['type' => 'separator', 'label' => 'FINANCE'],
    [
        'type'       => 'group',
        'label'      => 'Dépenses',
        'icon'       => 'banknotes',
        'permission' => 'manage expenses',
        'items'      => [
            ['label' => 'Lister les dépenses',    'route' => 'expenses.index'],
            ['label' => 'Ajouter une dépense',    'route' => 'expenses.create'],
            ['label' => 'Catégories de dépenses', 'route' => 'expense-categories.index'],
        ],
    ],
    [
        'type'       => 'group',
        'label'      => 'Comptes de paiement',
        'icon'       => 'building-library',
        'permission' => 'manage accounts',
        'items'      => [
            ['label' => 'Lister les comptes',     'route' => 'payment-accounts.index'],
            ['label' => 'Bilan',                  'route' => 'accounts.balance-sheet'],
            ['label' => 'Balance de vérification', 'route' => 'accounts.trial-balance'],
            ['label' => 'Flux de trésorerie',     'route' => 'accounts.cash-flow'],
        ],
    ],
    [
        'type'       => 'group',
        'label'      => 'Rapports',
        'icon'       => 'chart-bar',
        'permission' => 'view reports',
        'items'      => [
            ['label' => 'Profit / Perte',         'route' => 'reports.profit-loss'],
            ['label' => 'Achat & Vente',           'route' => 'reports.purchase-sale'],
            ['label' => 'Rapport clients',         'route' => 'reports.customers'],
            ['label' => 'Rapport fournisseurs',    'route' => 'reports.suppliers'],
            ['label' => 'Rapport de stock',        'route' => 'reports.stock'],
            ['label' => 'Ajustement de stock',     'route' => 'reports.stock-adjustment'],
            ['label' => 'Achat article',           'route' => 'reports.product-purchase'],
            ['label' => 'Ventes par article',      'route' => 'reports.product-sale'],
            ['label' => 'Bénéfice par catégorie',  'route' => 'reports.category-profit'],
            ['label' => 'Paiements d\'achat',      'route' => 'reports.purchase-payments'],
            ['label' => 'Paiements de vente',      'route' => 'reports.sale-payments'],
            ['label' => 'Rapport de dépenses',     'route' => 'reports.expenses'],
            ['label' => 'Rapport de caisse',       'route' => 'reports.pos'],
            ['label' => 'Journal d\'activité',     'route' => 'reports.activity'],
        ],
    ],
    ['type' => 'separator', 'label' => 'GESTION'],
    [
        'type'       => 'group',
        'label'      => 'Gestion des utilisateurs',
        'icon'       => 'users',
        'permission' => 'manage users',
        'items'      => [
            ['label' => 'Utilisateurs', 'route' => 'users.index'],
        ],
    ],
    [
        'type'       => 'group',
        'label'      => 'Contacts',
        'icon'       => 'identification',
        'permission' => null,
        'items'      => [
            ['label' => 'Fournisseurs', 'route' => 'suppliers.index', 'permission' => 'manage suppliers'],
            ['label' => 'Clients',      'route' => 'customers.index', 'permission' => 'manage customers'],
        ],
    ],
    ['type' => 'separator', 'label' => 'CONFIG'],
    [
        'type'       => 'group',
        'label'      => 'Paramètres',
        'icon'       => 'cog-6-tooth',
        'permission' => 'manage settings',
        'items'      => [
            ['label' => 'Entreprise',  'route' => 'settings.company'],
            ['label' => 'Entrepôts',   'route' => 'settings.warehouses'],
            ['label' => 'Factures',    'route' => 'settings.invoices'],
        ],
    ],
];
